### ISSUE TITLE
optparse-applicative, simple helpers

### ISSUE THREAD

**Issue by sorki** [stepcut/ircbot#4]
Thanks for merging the PR, few days ago I've also created `optparse-applicative` parser and `runBotWithParts` wrapper that allows to create bots with one liners.

https://gist.github.com/sorki/12cf3c0829d693421779d6ff4ec13569

What do you think? I can create a PR if it does look good to you.

**Comment by stepcut** [comment]
Looks great. I am not wild about line 123, but the only way I know to avoid that is to use `ThreadGroups`,

http://hackage.haskell.org/package/threads-0.5.1.6/docs/Control-Concurrent-Thread-Group.html#v:wait

But that adds an extra dependency to avoid something that perhaps isn't really a problem in the first place. Additionally, the use of `ThreadGroup` would need to be inserted into `simpleBot'` itself.

So, I guess I would accept a patch with or without the use of `ThreadGroup`

**Comment by sorki** [comment]
I'll take a look at threads and submit one. I've discovered it was missing `pingPart` too just now.
